rmdir /s /q "J:\Unreal Engine Projects\CapSim\Binaries"
rmdir /s /q "J:\Unreal Engine Projects\CapSim\Intermediate"
rmdir /s /q "J:\Unreal Engine Projects\CapSim\Saved"
rmdir /s /q "J:\Unreal Engine Projects\CapSim\.vs"
rmdir /s /q "J:\Unreal Engine Projects\CapSim\DerivedDataCache"
del /s /q "J:\Unreal Engine Projects\CapSim\CapSim.sln"